CREATE DATABASE CarNotesDb
GO
USE CarNotesDb
GO
CREATE TABLE Cars (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Manufacturer VARCHAR(50) NOT NULL,
	Color VARCHAR(30) NOT NULL,
	Engine VARCHAR(30) NOT NULL,
	Volume INT NOT NULL,
	BodyType VARCHAR(50) NOT NULL,
	Created DATETIME2 NOT NULL
);
GO
CREATE TABLE Notes (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Created DATETIME2 NOT NULL,
	Title VARCHAR(100) NOT NULL,
	Text VARCHAR(1000) NOT NULL,
	CarId INT NOT NULL FOREIGN KEY REFERENCES Cars(Id)
);
GO
CREATE TABLE Comments (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Created DATETIME2 NOT NULL,
	Author VARCHAR(50) NOT NULL,
	Text VARCHAR(200) NOT NULL,
	NoteId INT NOT NULL FOREIGN KEY REFERENCES Notes(Id)
)
GO